import { VillaType, ReviewType, BookingDetails } from '@/types';

export const DESTINATIONS = [
  {
    id: 'uluwatu',
    name: 'Uluwatu',
    description: 'Dramatic cliffs, world-class surf breaks, and magnificent ocean sunsets.',
    villaCount: 18,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'ubud',
    name: 'Ubud',
    description: 'The cultural heart of Bali surrounded by lush rainforests and rice terraces.',
    villaCount: 24,
    image: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'seminyak',
    name: 'Seminyak',
    description: 'Sophisticated beach clubs, upscale fine dining, and vibrant boutique nightlife.',
    villaCount: 32,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'canggu',
    name: 'Canggu',
    description: 'Bohemian coastal vibes, organic cafes, and trendy beachside retreats.',
    villaCount: 27,
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'nusa-dua',
    name: 'Nusa Dua',
    description: 'White sandy beaches, turquoise waters, and 5-star gated enclave luxury.',
    villaCount: 15,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'sanur',
    name: 'Sanur',
    description: 'Serene sunrise coastline, gentle sea breezes, and timeless Balinese calm.',
    villaCount: 12,
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80',
  },
];

export const FACILITIES_LIST = [
  { name: 'Private Pool', icon: 'Waves', category: 'Outdoor' },
  { name: 'Ocean View', icon: 'Eye', category: 'General' },
  { name: 'High-Speed WiFi', icon: 'Wifi', category: 'General' },
  { name: 'Breakfast Included', icon: 'Coffee', category: 'Service' },
  { name: 'Chef Kitchen', icon: 'Utensils', category: 'General' },
  { name: 'Free Parking', icon: 'Car', category: 'General' },
  { name: 'Air Conditioning', icon: 'Wind', category: 'General' },
  { name: 'Beach Access', icon: 'Sun', category: 'Outdoor' },
  { name: 'Airport Transfer', icon: 'Plane', category: 'Service' },
  { name: 'Spa & Wellness', icon: 'Sparkles', category: 'Wellness' },
  { name: 'Butler Service', icon: 'Bell', category: 'Service' },
  { name: 'Smart TV & Sound', icon: 'Tv', category: 'General' },
];

export const INITIAL_VILLAS: VillaType[] = [
  {
    id: 'villa-1',
    slug: 'ocean-serenity-villa-uluwatu',
    name: 'Ocean Serenity Villa',
    tagline: 'Cliffside Infinity Pool with Panoramic Sunset Vistas',
    description: 'Perched high upon the dramatic limestone cliffs of Uluwatu, Ocean Serenity Villa commands breathtaking 180-degree panoramas of the Indian Ocean. Designed in harmonious Balinese contemporary architecture, the estate features expansive open-air living pavilions, ironwood sun decks, and a private azure infinity pool that effortlessly merges into the horizon. Enjoy personalized five-star hospitality with our dedicated private butler, bespoke in-villa dining prepared by our master chef, and uninterrupted sunsets every evening.',
    shortDescription: 'Spectacular cliff-edge sanctuary in Uluwatu featuring a dramatic private infinity pool, dedicated butler, and infinite ocean horizon views.',
    location: 'Uluwatu, Bali',
    destination: 'Uluwatu',
    address: 'Jl. Pantai Suluban No. 88, Uluwatu, Pecatu, Bali 80361',
    latitude: -8.8295,
    longitude: 115.0934,
    pricePerNight: 3500000,
    cleaningFee: 300000,
    serviceFeePercent: 5.0,
    taxPercent: 11.0,
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    sizeSqm: 420,
    hasPrivatePool: true,
    villaType: 'Cliffside Luxury Villa',
    rating: 4.95,
    reviewCount: 128,
    isFeatured: true,
    isActive: true,
    cancellationPolicy: 'Free cancellation up to 7 days before check-in. Cancel within 7 days for a 50% refund minus service fees.',
    images: [
      { url: '/images/hero-villa.jpg', caption: 'Sunset infinity pool looking out over the Indian Ocean', isThumbnail: true },
      { url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80', caption: 'Master suite with private ocean terrace' },
      { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80', caption: 'Open-concept luxury living pavilion' },
      { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', caption: 'Sunken lounge and evening mood lighting' },
      { url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80', caption: 'Terrazzo soaking tub overlooking tropical garden' },
    ],
    facilities: ['Private Pool', 'Ocean View', 'High-Speed WiFi', 'Breakfast Included', 'Chef Kitchen', 'Free Parking', 'Air Conditioning', 'Beach Access', 'Airport Transfer', 'Butler Service'],
    rooms: [
      { name: 'Grand Ocean Master Suite', description: 'King bed, oceanfront terrace, standalone terrazzo bathtub, walk-in dressing room', price: 3500000, guestCapacity: 2, bedType: 'King Bed' },
      { name: 'Sunset Pavilion Room', description: 'King bed with direct pool access and private en-suite rainfall shower', price: 3200000, guestCapacity: 2, bedType: 'King Bed' },
      { name: 'Garden Palm Bedroom', description: 'Twin beds convertible to King, garden view patio, marble bathroom', price: 2900000, guestCapacity: 2, bedType: '2 Single or 1 King' },
    ],
  },
  {
    id: 'villa-2',
    slug: 'royal-bamboo-sanctuary-ubud',
    name: 'Royal Bamboo Sanctuary',
    tagline: 'Architectural Bamboo Masterpiece Immersed in Ubud Rainforest',
    description: 'An ethereal eco-luxury sanctuary nestled within the emerald river valley of Ubud. Crafted entirely of soaring curved bamboo and natural stone, this architectural jewel features multi-level open-air living, a curved stone plunge pool overlooking rushing river rapids, and peaceful meditation pavilions.',
    shortDescription: 'Award-winning architectural bamboo estate set amidst the sacred jungle valleys and terraced greenery of central Ubud.',
    location: 'Ubud, Bali',
    destination: 'Ubud',
    address: 'Jl. Raya Sayan No. 45, Sayan, Ubud, Gianyar, Bali 80571',
    latitude: -8.5069,
    longitude: 115.2426,
    pricePerNight: 4200000,
    cleaningFee: 350000,
    serviceFeePercent: 5.0,
    taxPercent: 11.0,
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 8,
    sizeSqm: 550,
    hasPrivatePool: true,
    villaType: 'Eco-Luxury Rainforest Villa',
    rating: 4.98,
    reviewCount: 94,
    isFeatured: true,
    isActive: true,
    cancellationPolicy: 'Free cancellation up to 14 days before check-in.',
    images: [
      { url: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80', caption: 'Bamboo vaulted living canopy over pool', isThumbnail: true },
      { url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80', caption: 'Private pool overlooking lush jungle' },
      { url: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80', caption: 'Forest-facing bamboo bedroom suite' },
      { url: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80', caption: 'Open-air bathroom with river stone tub' },
      { url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80', caption: 'Morning floating breakfast setup' },
    ],
    facilities: ['Private Pool', 'High-Speed WiFi', 'Breakfast Included', 'Chef Kitchen', 'Free Parking', 'Spa & Wellness', 'Butler Service', 'Airport Transfer'],
  },
  {
    id: 'villa-3',
    slug: 'the-glass-penthouse-seminyak',
    name: 'The Glass Penthouse Villa',
    tagline: 'Ultra-Modern Minimalist Chic in the Epicenter of Seminyak',
    description: 'Sleek floor-to-ceiling glass walls, polished marble, and bespoke contemporary furnishings define this high-glamour villa. Located just footsteps from Seminyaks premier beach clubs and Michelin-rated restaurants, yet entirely secluded behind towering tropical privacy gardens.',
    shortDescription: 'Contemporary designer villa featuring high ceilings, private lap pool, and walking proximity to Seminyak beach.',
    location: 'Seminyak, Bali',
    destination: 'Seminyak',
    address: 'Jl. Kayu Aya No. 12, Seminyak, Kuta, Badung, Bali 80361',
    latitude: -8.6874,
    longitude: 115.1558,
    pricePerNight: 2800000,
    cleaningFee: 250000,
    serviceFeePercent: 5.0,
    taxPercent: 11.0,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    sizeSqm: 280,
    hasPrivatePool: true,
    villaType: 'Modern Designer Villa',
    rating: 4.88,
    reviewCount: 86,
    isFeatured: true,
    isActive: true,
    cancellationPolicy: 'Free cancellation up to 5 days before check-in.',
    images: [
      { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80', caption: 'Modern glass facade and turquoise pool', isThumbnail: true },
      { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80', caption: 'Sunlit living and dining lounge' },
      { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80', caption: 'Chef gourmet kitchen and island bar' },
      { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80', caption: 'Master suite with courtyard view' },
      { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', caption: 'Evening illuminated poolside patio' },
    ],
    facilities: ['Private Pool', 'High-Speed WiFi', 'Breakfast Included', 'Chef Kitchen', 'Free Parking', 'Air Conditioning', 'Smart TV & Sound'],
  },
  {
    id: 'villa-4',
    slug: 'sunset-horizon-canggu',
    name: 'Sunset Horizon Estate',
    tagline: 'Bohemian Luxe Oasis with Lush Tropical Lagoon Pool',
    description: 'An expansive modern bohemian estate in trendy Canggu, boasting a 15-meter lagoon pool fringed with swaying coconut palms. Warm timber finishes, woven rattan accents, and Mediterranean sun-drenched daybeds provide the ultimate laid-back luxury stay.',
    shortDescription: 'Spacious tropical estate nestled close to Echo Beach with a lagoon-style pool and artisan interior decor.',
    location: 'Canggu, Bali',
    destination: 'Canggu',
    address: 'Jl. Batu Bolong No. 102, Canggu, Kuta Utara, Bali 80351',
    latitude: -8.6535,
    longitude: 115.1302,
    pricePerNight: 3900000,
    cleaningFee: 300000,
    serviceFeePercent: 5.0,
    taxPercent: 11.0,
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 8,
    sizeSqm: 480,
    hasPrivatePool: true,
    villaType: 'Tropical Bohemian Estate',
    rating: 4.92,
    reviewCount: 112,
    isFeatured: true,
    isActive: true,
    cancellationPolicy: 'Free cancellation up to 7 days before check-in.',
    images: [
      { url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80', caption: 'Lagoon pool and bohemian sun loungers', isThumbnail: true },
      { url: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80', caption: 'Spacious high-ceiling living space' },
      { url: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80', caption: 'Outdoor barbecue dining pavilion' },
      { url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80', caption: 'Boho luxury master bedroom' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80', caption: 'Luxury bathroom with twin copper basins' },
    ],
    facilities: ['Private Pool', 'High-Speed WiFi', 'Breakfast Included', 'Chef Kitchen', 'Free Parking', 'Air Conditioning', 'Beach Access', 'Airport Transfer'],
  },
  {
    id: 'villa-5',
    slug: 'azure-water-estate-nusa-dua',
    name: 'Azure Water Estate',
    tagline: 'Palatial Beachfront Haven with Private Coral Beach Access',
    description: 'Unrivaled 5-star oceanfront seclusion in Nusa Dua. Featuring private gated access directly to powdery white sand beaches, manicured royal lawn gardens, and butler service meeting the highest international standards.',
    shortDescription: 'Beachfront presidential-grade villa estate in Nusa Dua with direct shoreline access and royal gardens.',
    location: 'Nusa Dua, Bali',
    destination: 'Nusa Dua',
    address: 'Kawasan Pariwisata Nusa Dua Lot NW-3, Bali 80363',
    latitude: -8.8012,
    longitude: 115.2289,
    pricePerNight: 5500000,
    cleaningFee: 450000,
    serviceFeePercent: 5.0,
    taxPercent: 11.0,
    bedrooms: 5,
    bathrooms: 5,
    maxGuests: 10,
    sizeSqm: 650,
    hasPrivatePool: true,
    villaType: 'Oceanfront Presidential Villa',
    rating: 4.97,
    reviewCount: 79,
    isFeatured: true,
    isActive: true,
    cancellationPolicy: 'Free cancellation up to 14 days before check-in.',
    images: [
      { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80', caption: 'Grand estate pool facing turquoise ocean', isThumbnail: true },
      { url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80', caption: 'Palatial oceanfront living salon' },
      { url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80', caption: 'Formal dining for 10 guests' },
      { url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4b49?auto=format&fit=crop&w=1200&q=80', caption: 'Presidential master bedroom' },
      { url: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&w=1200&q=80', caption: 'White marble bathroom and steam shower' },
    ],
    facilities: ['Private Pool', 'Ocean View', 'High-Speed WiFi', 'Breakfast Included', 'Chef Kitchen', 'Free Parking', 'Air Conditioning', 'Beach Access', 'Airport Transfer', 'Butler Service', 'Spa & Wellness'],
  },
  {
    id: 'villa-6',
    slug: 'coral-heritage-villa-sanur',
    name: 'Coral Heritage Villa',
    tagline: 'Peaceful Coastal Colonial Charmer with Lush Lotus Ponds',
    description: 'Embrace traditional Balinese craftsmanship infused with timeless colonial grandeur. Surrounded by tranquil lotus ponds, mature frangipani trees, and just a gentle 3-minute stroll from Sanurs calm family-friendly lagoon beach.',
    shortDescription: 'Tranquil heritage colonial residence in Sanur featuring classical architecture and serene lotus ponds.',
    location: 'Sanur, Bali',
    destination: 'Sanur',
    address: 'Jl. Danau Tamblingan No. 72, Sanur, Denpasar Selatan, Bali 80228',
    latitude: -8.6948,
    longitude: 115.2631,
    pricePerNight: 2400000,
    cleaningFee: 200000,
    serviceFeePercent: 5.0,
    taxPercent: 11.0,
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    sizeSqm: 360,
    hasPrivatePool: true,
    villaType: 'Heritage Colonial Villa',
    rating: 4.85,
    reviewCount: 65,
    isFeatured: false,
    isActive: true,
    cancellationPolicy: 'Free cancellation up to 5 days before check-in.',
    images: [
      { url: 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1200&q=80', caption: 'Colonial veranda looking over the courtyard pool', isThumbnail: true },
      { url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80', caption: 'Teak wood antique decorated lounge' },
      { url: 'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1200&q=80', caption: 'Peaceful garden patio and reading daybed' },
      { url: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80', caption: 'Colonial style bedroom with canopy netting' },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80', caption: 'Garden open-air bathroom' },
    ],
    facilities: ['Private Pool', 'High-Speed WiFi', 'Breakfast Included', 'Free Parking', 'Air Conditioning', 'Beach Access'],
  },
  {
    id: 'villa-7',
    slug: 'cliffside-haven-bingin',
    name: 'Cliffside Haven Bingin',
    tagline: 'Raw Mediterranean Elegance Overlooking Bingin Surf',
    description: 'Sculpted into the limestone headlands above Bingin Beach, this sun-drenched sanctuary blends Aegean cycladic whitewash architecture with tropical Balinese textures. Features an infinity pool with front-row seats to world-famous surf breaks.',
    shortDescription: 'Mediterranean whitewashed cliff villa in Bingin with uninterrupted surf break views and sunset terrace.',
    location: 'Uluwatu, Bali',
    destination: 'Uluwatu',
    address: 'Jl. Pantai Bingin, Pecatu, Kuta Selatan, Bali 80361',
    latitude: -8.8058,
    longitude: 115.1132,
    pricePerNight: 3200000,
    cleaningFee: 280000,
    serviceFeePercent: 5.0,
    taxPercent: 11.0,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    sizeSqm: 240,
    hasPrivatePool: true,
    villaType: 'Cliffside Mediterranean Villa',
    rating: 4.91,
    reviewCount: 88,
    isFeatured: false,
    isActive: true,
    cancellationPolicy: 'Free cancellation up to 7 days before check-in.',
    images: [
      { url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80', caption: 'Whitewashed cliff pool looking over waves', isThumbnail: true },
      { url: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80', caption: 'Sun terrace and daybeds' },
      { url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80', caption: 'Ocean breeze open bedroom' },
      { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80', caption: 'Sunset dining table' },
      { url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80', caption: 'Stone vanity bathroom' },
    ],
    facilities: ['Private Pool', 'Ocean View', 'High-Speed WiFi', 'Breakfast Included', 'Air Conditioning', 'Beach Access'],
  },
  {
    id: 'villa-8',
    slug: 'jungle-canopy-retreat-tegallalang',
    name: 'Jungle Canopy Retreat',
    tagline: 'Secluded Glass Pavilion Over Sacred Rice Terraces',
    description: 'Suspended above the emerald mist of Tegallalang rice paddies, this villa offers ultimate rejuvenation. With an open-air heated stone hydrotherapy pool, private yoga shala, and soundscapes of cascading waterfalls.',
    shortDescription: 'Secluded luxury wellness pavilion overlooking the iconic terraced valleys of Tegallalang.',
    location: 'Ubud, Bali',
    destination: 'Ubud',
    address: 'Jl. Raya Tegallalang, Gianyar, Bali 80561',
    latitude: -8.4354,
    longitude: 115.2798,
    pricePerNight: 2900000,
    cleaningFee: 250000,
    serviceFeePercent: 5.0,
    taxPercent: 11.0,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    sizeSqm: 310,
    hasPrivatePool: true,
    villaType: 'Wellness Eco-Retreat',
    rating: 4.96,
    reviewCount: 104,
    isFeatured: false,
    isActive: true,
    cancellationPolicy: 'Free cancellation up to 7 days before check-in.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80', caption: 'Valley hydrotherapy pool at sunrise', isThumbnail: true },
      { url: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80', caption: 'Jungle facing bedroom' },
      { url: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80', caption: 'Zen open garden bathroom' },
      { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', caption: 'Yoga deck and meditation pavilion' },
      { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80', caption: 'Outdoor rainforest shower' },
    ],
    facilities: ['Private Pool', 'High-Speed WiFi', 'Breakfast Included', 'Free Parking', 'Spa & Wellness', 'Butler Service'],
  },
];

export const TESTIMONIALS: ReviewType[] = [
  {
    id: 'rev-1',
    villaId: 'villa-1',
    villaName: 'Ocean Serenity Villa',
    guestName: 'Claire & Julien Moreau',
    guestAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    guestCountry: 'France',
    rating: 5.0,
    title: 'An unforgettable honeymoon cliffside paradise',
    comment: 'From the moment our private driver met us at Denpasar until the emotional goodbye, every single detail was extraordinary. Waking up to the endless Indian Ocean with a floating breakfast served in our infinity pool was beyond magical.',
    date: '12 September 2026',
  },
  {
    id: 'rev-2',
    villaId: 'villa-2',
    villaName: 'Royal Bamboo Sanctuary',
    guestName: 'Alexander Hayes',
    guestAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    guestCountry: 'Australia',
    rating: 5.0,
    title: 'Architectural wonder in the heart of Ubud',
    comment: 'As an architect myself, living in the Royal Bamboo Sanctuary was pure inspiration. The airflow, the organic bamboo curves, and the sound of the Ayung River rapids below create an atmosphere that photos cannot fully capture.',
    date: '28 August 2026',
  },
  {
    id: 'rev-3',
    villaId: 'villa-5',
    villaName: 'Azure Water Estate',
    guestName: 'Sarah & David Tan',
    guestAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    guestCountry: 'Singapore',
    rating: 5.0,
    title: 'The gold standard of family luxury stays',
    comment: 'We stayed with our children and parents for a 5-day reunion. The private direct beach gate meant no crowded transfers, the chef accommodated all dietary wishes effortlessly, and the butler service was discreet and attentive.',
    date: '4 September 2026',
  },
];

export const INITIAL_BOOKINGS: BookingDetails[] = [
  {
    id: 'book-1',
    bookingCode: 'NV-2026-8921',
    villaId: 'villa-1',
    villaName: 'Ocean Serenity Villa',
    villaImage: '/images/hero-villa.jpg',
    location: 'Uluwatu, Bali',
    checkIn: '2026-10-10',
    checkOut: '2026-10-14',
    nightCount: 4,
    adults: 2,
    children: 0,
    infants: 0,
    totalGuests: 2,
    villaPrice: 14000000,
    cleaningFee: 300000,
    serviceFee: 700000,
    taxAmount: 1650000,
    discountAmount: 0,
    totalPrice: 16650000,
    status: 'CONFIRMED',
    guestName: 'Liam Hemsworth',
    guestEmail: 'liam.h@example.com',
    guestPhone: '+61 412 345 678',
    guestCountry: 'Australia',
    specialRequests: 'High floor master bedroom and arrival champagne please.',
    createdAt: '2026-09-15',
  },
  {
    id: 'book-2',
    bookingCode: 'NV-2026-7432',
    villaId: 'villa-2',
    villaName: 'Royal Bamboo Sanctuary',
    villaImage: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
    location: 'Ubud, Bali',
    checkIn: '2026-10-18',
    checkOut: '2026-10-21',
    nightCount: 3,
    adults: 4,
    children: 1,
    infants: 0,
    totalGuests: 5,
    villaPrice: 12600000,
    cleaningFee: 350000,
    serviceFee: 630000,
    taxAmount: 1493800,
    discountAmount: 1000000,
    totalPrice: 14073800,
    status: 'WAITING_PAYMENT',
    guestName: 'Sophia Lorenza',
    guestEmail: 'sophia@example.com',
    guestPhone: '+62 812 9876 5432',
    guestCountry: 'Indonesia',
    specialRequests: 'Floating breakfast on day 2.',
    createdAt: '2026-09-20',
  },
  {
    id: 'book-3',
    bookingCode: 'NV-2026-5120',
    villaId: 'villa-3',
    villaName: 'The Glass Penthouse Villa',
    villaImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    location: 'Seminyak, Bali',
    checkIn: '2026-09-01',
    checkOut: '2026-09-05',
    nightCount: 4,
    adults: 2,
    children: 0,
    infants: 0,
    totalGuests: 2,
    villaPrice: 11200000,
    cleaningFee: 250000,
    serviceFee: 560000,
    taxAmount: 1321100,
    discountAmount: 0,
    totalPrice: 13331100,
    status: 'CHECKED_OUT',
    guestName: 'Marcus Aurelius',
    guestEmail: 'marcus@example.com',
    guestPhone: '+44 7700 900077',
    guestCountry: 'United Kingdom',
    createdAt: '2026-08-20',
  },
];

export const PROMOTIONS = [
  {
    code: 'WELCOME20',
    description: '20% off for first-time luxury villa booking',
    discountType: 'PERCENTAGE',
    value: 20,
    minSpend: 5000000,
    isActive: true,
  },
  {
    code: 'ESCAPE10',
    description: '10% instant discount across all Uluwatu & Ubud villas',
    discountType: 'PERCENTAGE',
    value: 10,
    minSpend: 3000000,
    isActive: true,
  },
  {
    code: 'LUXURY500K',
    description: 'Rp 500.000 flat discount on stays 3 nights or more',
    discountType: 'FIXED_AMOUNT',
    value: 500000,
    minSpend: 4000000,
    isActive: true,
  },
];

export const FORMAT_IDR = (num: number): string => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    maximumFractionDigits: 0,
  }).format(num);
};
